---
#<% require 'kitchen-sync' %>

driver_plugin: vagrant

driver_config:
  require_chef_omnibus: true
  customize:
    cpus: 2
    memory: 1536
    cpuexecutioncap: 75

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  chef_omnibus_url: https://www.getchef.com/chef/install.sh

platforms:
  - name: ubuntu-12.04-base
    driver_config: &driver_config
      box: opscode-ubuntu-12.04
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
    run_list: &default_run_list
      - recipe[apt::default]
      - recipe[build-essential::default]
    attributes: &default_attributes
      mysql:
        bind_address: 'localhost'
        server_debian_password: 'password'
        server_repl_password: 'password'
        server_root_password: 'password'
        tunable:
          lower_case_table_names: 1
      nginx:
        default_site_enabled: false
        install_method: 'source'
        source:
          version: '1.4.4'
          conf_path: '/opt/pushit/nginx/nginx.conf'
          sbin_path: '/opt/pushit/nginx/sbin/nginx'

  - name: ubuntu-12.04-ruby
    driver_config: *driver_config
    run_list: *default_run_list
    attributes: *default_attributes

  - name: ubuntu-12.04-node
    driver_config: *driver_config
    run_list:  *default_run_list
    attributes: *default_attributes

suites:
  - name: user
    excludes:
      - ubuntu-12.04-base
      - ubuntu-12.04-node
    run_list:
      - recipe[pushit_test::user]
    data_bags_path:
      'test/data_bags'
    encrypted_data_bag_secret_key_path:
      'test/encrypted_data_bag_secret'

  - name: webserver
    excludes:
      - ubuntu-12.04-base
      - ubuntu-12.04-node
    run_list:
      - recipe[pushit_test::webserver]
    data_bags_path:
      'test/data_bags'

  - name: custom-vhost
    excludes:
      - ubuntu-12.04-base
      - ubuntu-12.04-node
    run_list:
      - recipe[pushit_test::custom-vhost]
    data_bags_path:
      'test/data_bags'
    encrypted_data_bag_secret_key_path:
      'test/encrypted_data_bag_secret'

  - name: database
    excludes:
      - ubuntu-12.04-base
      - ubuntu-12.04-node
    run_list:
      - recipe[pushit_test::database]
    data_bags_path:
      'test/data_bags'

  - name: nodejs
    excludes:
      - ubuntu-12.04-ruby
      - ubuntu-12.04-node
    run_list:
      - recipe[pushit_test::nodejs]
    data_bags_path:
      'test/data_bags'
    encrypted_data_bag_secret_key_path:
      'test/encrypted_data_bag_secret'

  - name: rubies
    excludes:
      - ubuntu-12.04-base
      - ubuntu-12.04-ruby
    run_list:
      - recipe[pushit_test::ruby]
    data_bags_path:
      'test/data_bags'

  - name: rails
    excludes:
      - ubuntu-12.04-base
      - ubuntu-12.04-node
    run_list:
      - recipe[pushit_test::rails]
    data_bags_path:
      'test/data_bags'
    encrypted_data_bag_secret_key_path:
      'test/encrypted_data_bag_secret'
