---
#<% require 'kitchen-sync' %>

driver:
  name: docker
  provision_command: curl -L http://www.opscode.com/chef/install.sh | bash
  socket: <%= ENV['DOCKER_HOST'] %>
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  chef_omnibus_url: https://www.getchef.com/chef/install.sh

platforms:
- name: ubuntu-12.04-base
  driver_config: &driver_config
    image: ubuntu:12.04
    platform: ubuntu
  run_list: &run_list
    - recipe[apt::default]
    - recipe[build-essential::default]
  attributes: &attributes
    mysql:
      bind_address: 'localhost'
      server_debian_password: 'password'
      server_repl_password: 'password'
      server_root_password: 'password'
      tunable:
        lower_case_table_names: 1
    nginx:
      default_site_enabled: false
      install_method: 'source'
      source:
        version: '1.4.4'
        conf_path: '/opt/pushit/nginx/nginx.conf'
        sbin_path: '/opt/pushit/nginx/sbin/nginx'


- name: ubuntu-12.04-ruby
  driver_config: *driver_config
  run_list:  *run_list
  attributes: *attributes

- name: ubuntu-12.04-node
  driver_config: *driver_config
  run_list:  *run_list
  attributes: *attributes
