---
#<% require 'kitchen-sync' %>

driver_plugin: vagrant

driver_config:
  customize:
    cpus: 2
    memory: 1536
    cpuexecutioncap: 75
  box: opscode-ubuntu-12.04
  box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box

provisioner:
  name: chef_zero
  require_chef_omnibus: 'latest'
  chef_omnibus_url: https://www.getchef.com/chef/install.sh
  data_bags_path:
    'test/data_bags'
  encrypted_data_bag_secret_key_path:
    'test/encrypted_data_bag_secret'

platforms:
  - name: ubuntu-12.04
    run_list: &default_run_list
      - recipe[apt::default]
      - recipe[build-essential::default]
    attributes: &default_attributes
      mysql:
        bind_address: 'localhost'
        server_debian_password: 'password'
        server_repl_password: 'password'
        server_root_password: 'password'
        tunable:
          lower_case_table_names: 1
      nginx:
        default_site_enabled: false
        install_method: 'source'
        source:
          version: '1.4.4'

suites:
  - name: user
    driver_config:
      box: <%= ENV['KITCHEN_BASE_BOX'] || opscode-ubuntu-12.04 %>
    run_list:
      - recipe[pushit_test::user]

  - name: webserver
    driver_config:
      box: <%= ENV['KITCHEN_RUBY_BOX'] || opscode-ubuntu-12.04 %>
    run_list:
      - recipe[pushit_test::webserver]

  - name: vhost
    driver_config:
      box: <%= ENV['KITCHEN_RUBY_BOX'] || opscode-ubuntu-12.04 %>
    run_list:
      - recipe[pushit_test::vhost]
    attributes:
      pushit_test_vhost_cert: dummy

  - name: custom_vhost
    driver_config:
      box: <%= ENV['KITCHEN_RUBY_BOX'] || opscode-ubuntu-12.04 %>
    run_list:
      - recipe[pushit_test::custom_vhost]

  - name: database
    driver_config:
      box: <%= ENV['KITCHEN_RUBY_BOX'] || opscode-ubuntu-12.04 %>
    run_list:
      - recipe[pushit_test::database]

  - name: nodejs
    driver_config:
      box: <%= ENV['KITCHEN_BASE_BOX'] || opscode-ubuntu-12.04 %>
    run_list:
      - recipe[pushit_test::nodejs]

  - name: rubies
    driver_config:
      box: <%= ENV['KITCHEN_NODE_BOX'] || opscode-ubuntu-12.04 %>
    run_list:
      - recipe[pushit_test::ruby]
    # verifier:
    #   name: shell
    #   command: rspec -c -f d -I serverspec test/integration/rubies/serverspec/ruby_spec.rb

  - name: rails
    driver_config:
      box: <%= ENV['KITCHEN_RUBY_BOX'] || opscode-ubuntu-12.04 %>
    run_list:
      - recipe[pushit_test::rails]
