---
#<% require 'kitchen-sync' %>

driver:
  name: docker
  provision_command: curl -L http://www.opscode.com/chef/install.sh | bash
  socket: <%= ENV['DOCKER_HOST'] %>
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  chef_omnibus_url: https://www.getchef.com/chef/install.sh

platforms:
- name: ubuntu-12.04-base
  driver_config: &driver_config
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
  run_list: &run_list
    - recipe[apt::default]
    - recipe[build-essential::default]
  attributes: &attributes
    mysql:
      bind_address: 'localhost'
      server_debian_password: 'password'
      server_repl_password: 'password'
      server_root_password: 'password'
      tunable:
        lower_case_table_names: 1
    nginx:
      default_site_enabled: false
      dir: '/opt/pushit/nginx'
      log_dir: '/opt/pushit/nginx/log'
      pid: '/opt/pushit/nginx/run/nginx.pid'
      install_method: 'source'
      source:
        version: '1.4.4'
        conf_path: '/opt/pushit/nginx/nginx.conf'
        sbin_path: '/opt/pushit/nginx/sbin/nginx'


  - name: ubuntu-12.04-ruby
    driver_config: *driver_config
    run_list:  *default_run_list
    attributes: *default_attributes

  - name: ubuntu-12.04-node
    driver_config: *driver_config
    run_list:  *default_run_list
    attributes: *default_attributes
